### ISSUE TITLE
Configuration (optional)

### ISSUE THREAD

**Issue by andymckay** [integrations/jira#10]
- [ ] Allows GitHub Enterprise instances to integrate with JIRA Enterprise

**Comment by fuxx** [comment]
Hey @andymckay any news on the topic :) ? 

We are in the process of migrating our TRAC system which is coupled to GitHub Enterprise to JIRA and Confluence and we really would love to keep GitHub Enterprise in our environment instead of Bitbucket but the current connector is not very nice regarding the overview of Commits so this one would be really a boost.

Is their an estimation when the API could be available to JIRA to continue on the integration?

**Comment by andymckay** [comment]
Sorry @fuxx I'm not working on this project myself anymore, so I'm not sure of the timelines for this one. If you've got a GitHub Enterprise account, then maybe contacting your GitHub sales representative could help. Either way you've commented on this issue so perhaps some people who are working on the project might be able to give an update.

**Comment by tcbyrd** [comment]
Hi @fuxx! We are definitely working on enterprise support, but nothing to announce just yet. This integration uses a new API from Atlassian that’s not yet available in Jira server, but the good news is we’ve designed this to eventually work on-prem, so hopefully once the APIs are available it won’t take much work to setup.

**Comment by rodrigoaliste** [comment]
What about Jira Cloud to GitHub Enterprise Server?

**Comment by bryancross** [comment]
Any update on this?  This 'Jira' seems to be getting pretty popular.....

**Comment by kleinen** [comment]
@tcbyrd Just noticed the convo on this issue.  My company is also looking to integrate Jira Cloud with GitHub Enterprise.  I'm hoping that since it has been nearly two years since your last comment that maybe some traction or progress has been made.

**Comment by rachellerathbone** [comment]
HI @andymckay. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by rachellerathbone** [comment]
Hey @andymckay as we are currently in the process of migrating from Jira Enterprise (Jira Server) to Jira Cloud, this issue is no longer relevant so going to close it out. If you have any suggestions in the GitHub/Jira Cloud space, please feel free to open a new issue.
