### ISSUE TITLE
Jira issue links not unfurled in PR body

### ISSUE THREAD

**Issue by bkeepers** [integrations/jira#120]
If you type `[JI-123]` in an issue body or comment, it will get linked to the Jira issue. If you type it in the Pull Request body, it does not.

**Comment by andymckay** [comment]
@gimenete is it possible to separate this issue from #121? We are waiting for feedback on that one, but it seems that linking up a Pull Request body has nothing to do with the DevInfo API mentioned in #121.

**Comment by gimenete** [comment]
Sure
