### ISSUE TITLE
Developement Panel is not available

### ISSUE THREAD

**Issue by charlymr** [integrations/jira#137]
### Description:
When linking my organisation to Jira Cloud with the new GitHub plugin, everything seems to works and I see my organisation. I used to do it the old way and it was working.

### Actual  Result:
The development panel is not present. I use to have all my commit, branches, pull request and now nothing is there, even after 3 days! That is very frustrating!

I have been searching and don't seems to find a way to sort that. Tried many different thing, removing the account, putting it back... It's just not here :( 

 ###  Expected result:
After migrating, installing the new plugin and deleting the old DVCS link I would see the development section in my ticket as I use too. See screenshot.

![issue with dev panel](https://user-images.githubusercontent.com/356901/47662870-13e5ab80-db9c-11e8-8c24-374f1fc537e8.png)

**Comment by charlymr** [comment]
It actually came after 4 days!

**Comment by tcbyrd** [comment]
@charlymr Sorry it took so long! We're working on improving this. Do you know how many repositories you added to the installation? To prevent rate limiting issues, the integration processes a single repo at a time, so it doesn't post the event to Jira that the migration is complete until all repositories have migrated. It's not supposed to hide the DVCS information until the migration is complete, but we did find a condition where it would post the migration event before all data was migrated.. That bug has been fixed.

**Comment by charlymr** [comment]
@tcbyrd actually that's the thing, I didn't know I shouldn't have remove the DVCS link so my mistake was after installing the plugin I delete the link.

I have about 100 repositories on my account ( Including fork) SO yes I do have a lot.

Anyway all back to normal now. Maybe in the migration process, just mention not to remove the DVCS or have some indicator saying when we can remove the link.
