### ISSUE TITLE
"Get Started" in Jira addons leads to an error page

### ISSUE THREAD

**Issue by joshma** [integrations/jira#138]
I've done the following:
- Installed the Jira integration on GitHub marketplace
- Installed the GitHub add-on in Jira

However, when it takes me to the post-install setup (https://XXX.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page), I see an iframe with a 500 in it and an "App is not responding" message:

![image](https://user-images.githubusercontent.com/64739/47693252-308edd00-dbb6-11e8-854e-0f563a5c3fd1.png)

The iframe links to a page like https://jira-integration-production.herokuapp.com/jira/configuration?user_id=...

Is this something strange about my particular installation, or is the integration down right now?

**Comment by tcbyrd** [comment]
@joshma It seems to be up for most users. Can you try uninstalling the integration from Jira (you can leave it installed on GitHub) and reinstalling it from within you Jira instance. You can go directly to the integration page from `https://<instance>.atlassian.net/plugins/servlet/upm/marketplace/plugins/com.github.integration.production`.

**Comment by drmaxx** [comment]
I have the exact same Issue. Even after re-installing the Addon in Jira and trying the link provided.

**Comment by joshma** [comment]
Ah...so I swear I've reinstalled a few times before and it didn't work. This time, it worked, though. :)

@drmaxx worth trying reinstalling again, it might be some transient issue.

**Comment by tcbyrd** [comment]
https://github.com/integrations/jira/pull/118 included some fixes to how that page loads (since it's where you can re-trigger a sync job), so reinstalling before that was deployed may not have worked correctly. Glad it's working for you now!

**Comment by joshma** [comment]
In trying to troubleshoot #143, I uninstalled the Jira addon and reinstalled it. The same behavior as before is back - a 5xx iframe and "App is not responding. Wait or cancel?"

Is there some regression in the integration! (Thanks in advance for the help!)

**Comment by gb-ckedzierski** [comment]
Same issue here. Installed the plugin and clicked on 'configure' now I get the above error.

**Comment by tcbyrd** [comment]
Hey all. Sorry for the delay here. I've been trying to recreate this issue and it seems to not be consistently happening. I was able to recreate it when installing directly from the Atlassian Marketplace, but installing it manually from the descriptor works every time.

Anyone having this issue, could you try manually adding the app from this descriptor URL? https://marketplace-cdn.atlassian.com/files/1.1.0-AC/artifact/descriptor/345df622-da2f-4b1f-a5a3-068806c57031/atlassian-connect.json

You can do that on this screen: 
![image](https://user-images.githubusercontent.com/13207348/49178887-fa608c80-f31e-11e8-925f-c9a9b68ebb57.png)

The Marketplace should be using that descriptor, but it seems like there are scenarios where we never get the install event when going through the marketplace flow. I just want to confirm if this is definitely related to Marketplace flow vs manually providing the descriptor.

**Comment by gb-ckedzierski** [comment]
@tcbyrd we installed through the marketplace.

**Comment by tcbyrd** [comment]
@gb-ckedzierski Can you try the manual installation option from the URL I provided? That's the descript from our Marketplace listing, so it's the exact same app. I just want to verify if there's a bug specifically with the Marketplace flow.

**Comment by gb-ckedzierski** [comment]
@tcbyrd Sorry for the delay. We were able to install it that way, and it seems to be working. Thanks for the workaround. Please let me know if there's any other information you would need.

**Comment by drmaxx** [comment]
Just tried to do a manual installation with the Link provided above. I still get exactly the same error message as joshma got in the first post.

**Comment by tcbyrd** [comment]
Thanks all. Looks like there's a race condition here where sometimes we don't get the installation event quick enough. Patch will be out ASAP.

**Comment by tcbyrd** [comment]
Ok this has been deployed in production and I tested uninstalling/reinstalling the app multiple times and everything is working fine. If anyone is still having problems with this error screen, please let us know, but I think that race condition was the cause of all of these.
