### ISSUE TITLE
Real-time synchronisation does not work for my jira/github integration

### ISSUE THREAD

**Issue by KAbakumovAtl** [integrations/jira#143]
My Jira instance: https://kabakumov.atlassian.net
I've integrated it with my account and, particularly, with https://github.com/KAbakumovAtl/NewTestRepo repository.

1) I have created TEST-13 and TEST-14 issues
2) I've created new branch https://github.com/KAbakumovAtl/NewTestRepo/tree/TEST-13-merge-test-branch
3) I've pushed 2 commits consequentially to my branch with the following messages:

- TEST-13 #inprogress #comment start (https://github.com/KAbakumovAtl/NewTestRepo/commit/e2e6f8bcc20db616217c734bd94f2d1f0fe1b5e2)
- TEST-14 #done test (https://github.com/KAbakumovAtl/NewTestRepo/commit/a71c887178b6b9dbf9ccefe1f6860d9e8b76c795)

**ER:** I see these branch and commit on "TEST-13" issue and single commit on the "TEST-14" issue
**AR:** Information not synchronised. (Also, no requests to DevInfo API noticed on Jira side)

4) I've created a pull request to merge branch to master
5) I've merged the branch to the master using squash commit.

**AR:** Still no information on the issues

6) I went to GitHub add-on  configuration page and triggered synchronisation manually
**ER:** 2 commits on TEST-13 (merge commit and commit e2e6f8bcc2), branch and pull request. 1 commit (a71c887178b6) on TEST-14 issue.
**AR:** I saw branch, merge commit and pull request on TEST-13 issue, I saw branch on my TEST-14 issue. No commits from the branch on either TEST-14 or TEST-13 issues.

**Comment by joshma** [comment]
I'm experiencing the same thing, except step 6 - even after hitting retry on https://XXX.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page, a PR I created w/ the issue key in the PR title, branch name, and commit doesn't get linked to the issue.

(We're using the new Jira issue view, for what it's worth. I tried turning it off but it didn't help.)

**Comment by ACyphus** [comment]
Hey @KAbakumovAtl & @joshma 

For direct support on this integration you need to contact the GitHub Support team: 

https://github.com/integrations/jira#questions-need-help
