### ISSUE TITLE
Consider sending merge commits with "preventTransitions=true" flag

### ISSUE THREAD

**Issue by KAbakumovAtl** [integrations/jira#144]
When we do squash merge, we might have all commits messages from the branch copied to the merge commit.

In this case we might potentially have:
1) If there were any "smart commits" commands in the branch commits messages, then they might be executed again because they occurred in the smart commit
2) If there are some transitions triggers by submitting new commit configured in the issue workflow, then transitions might happen again. 

To prevent it, please consider sending merge commit in a separate DevInfo API request with "preventTransitions=true" flag set.

**Comment by rachellerathbone** [comment]
A PR for this request has been approved and will be deployed to prod in the coming week.
