### ISSUE TITLE
Link PR by Branch Name

### ISSUE THREAD

**Issue by mike-stewart** [integrations/jira#153]
We are using this integration as a replacement for the JIRA DVCS integration. One of the features we liked with it was that it would create links in JIRA to the PR if the branch name of the PR matched the JIRA key. This integration only links based on the PR title.

This integration already shows branches and commits, so including the branch name in the PR search would help catch PRs that might not have been named correctly, but clearly are related to the issue.

**Comment by alfonsochartier** [comment]
+1 this would be very useful. Note that the documentation states that the PR should be picked up if you name the branch with the JIRA issue, however I tested this and it does not appear to be the case (only picks up the branch): https://confluence.atlassian.com/jirasoftwarecloud/referencing-issues-in-your-development-work-777002789.html

**Comment by ninoalloy** [comment]
Yes please this would be great because it would not only match the behaviour of the now old DVCS connector but also keep the business process simpler by requiring the developer to only add the issue key in the branch name without having to remember to do the same for the pull request

**Comment by cmcnicholas** [comment]
This used to work with a Jira key as a part of:

- PR title (still working)
- PR description
- branch title
- any new commit message associated with the branch

This greatly simplified the process for developers.

**Comment by BrianAI** [comment]
This is a very important part of the workflow that was set up as part of the roll out and integration of these two tools.  Really looking forward to seeing this come back!

**Comment by laurenbrandstein** [comment]
This! We were using these workflow hooks and found it a big value-add both for the engineering team to avoid wasting time on manual steps or forgetting things, as well as for product and design (since issues were kept up-to-date more often with the automation). Please bring it back! 🙏

**Comment by zakness** [comment]
Our team really misses this feature from DVCS as well! Our PRs get automatically converted to release notes, so we actually have our engineers explicitly remove the branch name from the PR title to make them more readable for non-technical folk.

**Comment by johnBartos** [comment]
+1 for this. We run a public repo backed by a private Jira board. It's a leaky abstraction to have ticket numbers in the titles; we don't want to expose our sprint details to the world.

**Comment by cah-dunn** [comment]
👍

**Comment by WORMSS** [comment]
I added all the subtasks IDs in commits messages of the commits (and also the PR description) and the tasks were not updated like they used to.
Now it ends up all ends up in a giant unreadable Pull Request Title. This is unmanageable.
Needs to go back to the DVCS featureset.

**Comment by ACyphus** [comment]
This has shipped over here: https://github.com/integrations/jira/pull/173
