### ISSUE TITLE
Add a visual indicator that the Retry button was clicked

### ISSUE THREAD

**Issue by ACyphus** [integrations/jira#156]
Clicking the Retry button inside the integration configuration in Jira should give an indicator that the button was clicked and that something is happening.

Here is a screenshot of where the button is located:

![screen shot 2018-12-10 at 11 55 09](https://user-images.githubusercontent.com/983880/49751234-8a34fd80-fc72-11e8-8dad-72989f47b8e6.png)

Currently clicking the button gives zero feedback.

**Comment by rachellerathbone** [comment]
Closing this as the UI has since changed. Users now click 'submit' and the page refreshes when the requests are sent.
