### ISSUE TITLE
Jira bot duplicating ticket links

### ISSUE THREAD

**Issue by returnlytom** [integrations/jira#159]
Similar to #141, the Jira bot is duplicating links to tickets. Please see this gif for a reproduction:

![link_inject](https://user-images.githubusercontent.com/22224829/50033902-d51d8f00-003d-11e9-9095-c4c27207f568.gif)

**Comment by tcbyrd** [comment]
This is an interesting issue. I think the best way to solve for it is we just don't unfurl to the same syntax we use within the unfurled link.

What would you think if we instead unfurled to something like this: [jira/TES-123](https://example.com/browse/TES-123). This follows the way github unfurls links (e.g. https://github.com/integrations/slack/issues/1). Done this way it's also visually more clear that the link will take you to Jira.

**Comment by tcbyrd** [comment]
Check out #161 for a proposed solution.

**Comment by returnlytom** [comment]
@tcbyrd Love it! Nice work, thanks for the prompt turnaround :)

**Comment by returnlytom** [comment]
Closed by #165
