### ISSUE TITLE
Development panel doesn't appear

### ISSUE THREAD

**Issue by joshma** [integrations/jira#162]
I'm experiencing a similar issue as #137 but with just 1 repo - the Development panel never appears.

Here's what I've done:
1. Set up the Jira app in Github, and the Github app in Jira
2. Created a PR titled `[BNCH-5458] Testing` (BNCH-5458 is an existing issue we have)
3. Verified that some part of this works - if I type `[BNCH-5458]` in a PR body, it gets linkified by the `jira` bot.
4. However, in visiting BNCH-5458 on Jira, nothing appears related to the PR:

![image](https://user-images.githubusercontent.com/64739/50667362-bbe96d80-0f6d-11e9-92b9-636d73b34359.png)

**Comment by ACyphus** [comment]
@joshma What is your sync status? You can find it by going to Jira Settings -> Add-ons -> Manage Add-ons -> GitHub -> Get started.

https://github.com/integrations/jira/blob/5eeb4f36ae26c7c107a2199b3d67d077521cfdf3/SUPPORT.md#sync-status-not-reaching-complete

**Comment by joshma** [comment]
Ah...it's currently (still) ACTIVE - I'll retry, although I suspect it will still hang again.

**Comment by tcbyrd** [comment]
@joshma We found some issues with payloads that were getting rejected from Jira that was preventing the sync from completing. These were just deployed this evening (#164, #163), so if you can hit the retry button on more time, it should pick from where it got stuck before. Let us know if it's not finished in the next day or two.

**Comment by joshma** [comment]
Will retry and check back in, thanks.

**Comment by joshma** [comment]
Works now, thank you for your help!
