### ISSUE TITLE
No change in either github or jira after several installs 

### ISSUE THREAD

**Issue by clmcgrath** [integrations/jira#168]
I have tried installing this several times on our Enterprise Cloud account and none of the expected features seem to be showing up in either Github or Jira 

no development pane,  no commits tab ,  issue linking doesn't seem to be working in github either

**Comment by ACyphus** [comment]
> I have tried installing this several times on our Enterprise Cloud account and none of the expected features seem to be showing up in either Github or Jira
> 
> no development pane, no commits tab , issue linking doesn't seem to be working in github either

👋 @clmcgrath we have some support documentation that may be useful here:

https://github.com/integrations/jira/blob/ffbf1e8bc346c2265d616e965e62ddad5e981768/SUPPORT.md#sync-status-not-reaching-complete

What is the status of your integration?

**Comment by clmcgrath** [comment]
looks like it started working in jira in the last day or so 
but sync is taking a long time to complete , issue links taking 15-20 minutes to show up

**Comment by ACyphus** [comment]
Thanks for the update @clmcgrath. What is the current sync status displayed in the integration settings?

**Jira Settings -> Add-ons -> Manage Add-ons -> GitHub -> Get started**

**Comment by ACyphus** [comment]
Closing this. If this is still a problem please re-open the issue.
