### ISSUE TITLE
"add-ons" -> "apps"

### ISSUE THREAD

**Issue by mausch** [integrations/jira#169]
https://github.com/integrations/jira/blob/master/README.md#installation-from-atlassian  talks about "add-ons" but my Jira ("Jira d8bbfd3f" according to the "about" page, it's hosted by Atlassian) says "apps" instead of "add-ons". Not sure if my instance is older or newer than what the documentation expects? Does this have any impact on this integration? (it does not work at all on my instance). Is any of this worth documenting?

**Comment by tcbyrd** [comment]
Thanks @mausch. Guess they changed it after I wrote the docs! 😄
