### ISSUE TITLE
Only new commits are linked to Jira tickets

### ISSUE THREAD

**Issue by nvmwill** [integrations/jira#180]
Hi there,

I've just replaced the old DVCS account link from Jira Cloud to Github with the app-based version.

Now that the app is working, only new commits are showing up in the Development Information panel in Jira tickets. All of the commit links that were visible in tickets prior to the app installation seem to have been lost.

Is there a way to re-sync or re-scan the entire commit history for my Github organisation account, so that I can restore the older commit links?

Thanks!

Will

**Comment by tcbyrd** [comment]
Hi @nvmwill! This should happen automatically when the new integration is installed as long as all repositories in your Organization that have smart commits are part of the installation. Depending on how many repositories/commits it could take a few hours, but even for large installations it should complete in a few hours. If the old commits still haven't showed up, you can go back to the app page and there should be a button to "retry" the sync. This will trigger a scan of all repositories in the installation. If you need to double check which repositories are part of the installation, click the "Configure" link and that should take you to a page where you can add/remove repositories to that installation.

If none of the above works, we'll have to debug your specific installation, so you may want to [contact support](https://github.com/contact?form%5Bsubject%5D=Re:+GitHub%2BJira+Integration) and provide us your Jira instance and GitHub Organization.

**Comment by nvmwill** [comment]
Hey Tommy - thanks for the response! I'm still seeing the issue after trying the re-sync button, so I'll use that support link and keep my fingers crossed!

Cheers

**Comment by alainbryden** [comment]
Our organization has the same problem. We tried the full re-sync from the JIRA plugin post-install page instance (`Full - Rediscover your GitHub repositories and perform another full sync. Use this is you've changed the configuration on GitHub or would otherwise like to rescan all repositories.`) and it didn't help. I've also submitted a GitHub Developer Support issue.

**Comment by yaeldaum** [comment]
We are having the same issue, I submitted a support issue. Hope to get an answer soon

**Comment by alainbryden** [comment]
For what it's worth, the problem ended up resolving itself when I submitted a "Retry > Full" from JIRA at
 https://yourorganization.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page
It just took a long time (~6 hours) for the effects to become apparent.

**Comment by nvmwill** [comment]
I got past this issue - should have left a comment in here to say this. I ended up uninstalling and re-installing the Github app in Jira and that did the trick. I did need to wait a while for the re-sync to complete (probably due to a scan of the long commit history) but all of the historical commits are now linked up to their tickets in Jira.

**Comment by yaeldaum** [comment]
@alainbryden, thank you. A full sync actually solved this issue.

**Comment by scepticulous** [comment]
It seems as if @nvmwill and @yaeldaum were able to fix their issue by re-installing and re-syncing it. 
Closing this for now.
Feel free to add a comment, if there is anything else to do related to this issue.
