### ISSUE TITLE
JIRA server support

### ISSUE THREAD

**Issue by Thijzer** [integrations/jira#183]
I'm wondering and couldn't find any support for JIRA server yet.
Is this in the works or should I look somewhere else?

Many thanks

**Comment by tcbyrd** [comment]
@Thijzer Jira server support is dependent on the new DevInfo API being available. The current DVCS connector should offer much of the same functionality this new integration provides though, and we've written this in a way that it should be able to be adapted to Jira Server once the new API endpoints are available.

**Comment by brianjmurrell** [comment]
So why close this issue then?

**Comment by brianjmurrell** [comment]
Does "JIRA server" in the description refer to non-cloud (i.e. self-run) standalone Jira instances?

**Comment by tcbyrd** [comment]
Yeh that's how I interpret Jira server. We are working on adding support for Jira Cloud <-> GitHub Enterprise Server next, but my understanding is DVCS will still be the way to support these workflows in Jira Server for now.

**Comment by jefersonchaves** [comment]
Hey, @tcbyrd:  is there a hope to get Jira Server with GitHub Cloud?

**Comment by tcbyrd** [comment]
> Jira Server with GitHub Cloud?

This repo is for an integration that connects to the DevInfo API that replaced the DVCS connector in Jira Cloud. To my knowledge, the DVCS connector is [still supported in Jira Server](https://confluence.atlassian.com/adminjiraserver080/linking-a-bitbucket-or-github-repository-with-jira-967896966.html), and would be the recommended solution in that scenario.

**Comment by x4e-jonas** [comment]
DVCS cannot link commit messages in GitHub to Jira Server.
