### ISSUE TITLE
Feature request: Support forks

### ISSUE THREAD

**Issue by jdnrg** [integrations/jira#186]
I would like a function to delegate admin hooks for forked private repos to the owner.

Suppose you have developers working on forks of a company repo in github.
Suppose they are using a personal account and want to use smart commits for jira.
In this case it becomes tedious to setup.

In order to have your personal fork watched by jira, you need to add it to the repository as admin. The admin does not have access to the persons repository. So we need to grant temp admin of jira to the user to setup the plugin.

First you need to setup a meeting with the jira administrator and get temporary admin rights to install your repo.
If you have a shared account, otherwise you will have to grant jira access to all your repos or have to pick a subset of your repos to share. 

In that case if new central repos are added this exercise will have to be repeated.

The github feature would allow for forks to be monitored as well.

**Comment by jdnrg** [comment]
Posted in community forum here https://community.atlassian.com/t5/Jira-discussions/Feature-request-for-Jira-Github-Integration-for-Forked-repos/m-p/1055923#M7136

**Comment by rachellerathbone** [comment]
Hi @jdnrg. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.
