### ISSUE TITLE
Unwanted issue transitions/smart commits during Initial Sync

### ISSUE THREAD

**Issue by KAbakumovAtl** [integrations/jira#192]
According to the code, for any request to **/rest/devinfo/0.10/bulk** endpoint, **preventTransitions** parameter is always set to "**false**". 

As a result, we might have transitions and smart commits triggered during initial sync. On Jira side, we got some customer tickets about unwanted transitions which happen on migration from DVCS to GitHub App. 

To fix this problem **preventTransitions** flag shall be set to "**true**" for the initial sync requests. (Because we don't want to transition issues on events, which happened in the past) For regular sync requests, which made after initial sync, this flag shall be set to "**false**" to allow transition and smart commits happen if commit was made recently.

**Comment by nikkahall** [comment]
Hi - is there an anticipated completion date for the resolution to this issue?

**Comment by nikkahall** [comment]
Hi - the last comment on this was 22 days ago.  Is there any update? Or someone I can contact regarding resolution schedule?

**Comment by psilveirapsilveira** [comment]
Hi @tcbyrd,
Can you help us on getting an update on this case?

**Comment by scepticulous** [comment]
Hi 👋 ,
thanks for reporting the issue.
We are going to discuss potential solutions for this issue. Once we have an idea what the best approach would be, we will comment here.

**Comment by tcbyrd** [comment]
Hey all. This has now been resolved in #246 and deployed to production this morning. Initial sync should no longer trigger transitions.
