### ISSUE TITLE
safe to delete DVCS configuration?

### ISSUE THREAD

**Issue by bfallik** [integrations/jira#196]
Apologies if this is more of a user question than a technical issue. Please redirect me if there's a better place to ask this.

We're in the process of migrating from the old DVCS Connector to this new marketplace app. After installing the "Jira for github" plugin and once the initial sync transitions to the COMPLETE state, is it safe to delete the old DVCS configuration? Can/should I remove it from Jira and delete the associated Github OAuth apps?

This question wasn't addressed in any of the documentation I saw.

Thanks,
brian

**Comment by vkarri-invn** [comment]
Yes. it worked for me

**Comment by jnraine** [comment]
@bfallik Atlassian will remove it automatically eventually—if they haven't already—but you can safely remove it at any time.

> We will eventually stop syncing the DVCS Connector account for you, we kept it in the background in case of any issues that might have popped up, we could switch back over (bit of an insurance policy for making sure your data was safe). Everything is looking very stable so you will see us start to disable these if you haven't already.
>
>However, you are always welcome to just go ahead and delete the GitHub account on the DVCS Accounts page that you have connected. 
>
>– [Comment from Atlassian](https://community.atlassian.com/t5/Jira-articles/Everything-you-need-to-know-about-migrating-from-the-DVCS/ba-p/945910#M1207)
