### ISSUE TITLE
Not Syncing with JIRA on Commit

### ISSUE THREAD

**Issue by bmckinney00** [integrations/jira#200]
Whenever I commit to a feature branch in github that is in a repo that is associated with JIRA, the corresponding JIRA issues is not being updated.  The feature branch is named feature/JIRA-XXX-setup-integration.  The commit message is "[JIRA-XXX] #time 1h #comment Added new logic".  The corresponding JIRA issue is not updated with information whenever I push to GitHub.  If I go into JIRA -> Settings -> Manage Apps -> GitHub -> Get started, the status shows COMPLETE.  If I change the Retry field to Full and Submit, I can wait a few seconds and the status is now COMPLETE again.  Once this happens, the corresponding JIRA issue is updated.  So, it appears that the integration is configured correctly.  It is just not firing correctly whenever a commit happens in GitHub.

**Comment by rachellerathbone** [comment]
Hey @bmckinney00. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Please let me know if you are still facing this issue so I can help.

**Comment by bmckinney00** [comment]
This issue is resolved.  I honestly don't remember if there was a fix for
this or if it just started working.

Bryan McKinney
Analyst/Programmer Sr
Wake Forest University
Information Systems
(336) 758-3099

**Comment by rachellerathbone** [comment]
Thanks for letting me know. Glad your issue was resolved. Will close this issue but please open issues for anything else you run into. We're assigning someone from the team each week to look into reviews so response time will increase drastically.
