### ISSUE TITLE
Configuration to prevent Jira issues transitions?

### ISSUE THREAD

**Issue by gjabouley-invn** [integrations/jira#209]
Hello

we have deployed recently the integration on our Github Organization / Jira Cloud.

It seems it is not possible, on Github App side, to prevent JIRA issue status transition while keeping the integration enabled for a repository.

Is it possible to configure, on Jira side (maybe at workflow level), to prevent issue status transition when receiving event on API?

Reason is we have different kind of projects on Jira:
- Development projects, where this behavior is fine
- QA projects, where we want to disable this auto transition feature. Developers can refer to QA Jira issues, and it is good to have the link reference created in Jira, but the issue status shall never be modified automatically

**Comment by benoit-lateltin** [comment]
You have to disable the **trigger** in your Jira worflow

<img width="1266" alt="Screenshot 2021-02-10 at 19 08 05" src="https://user-images.githubusercontent.com/819411/107552061-50097280-6bd3-11eb-9baf-41c83d3deb59.png">

**Comment by rachellerathbone** [comment]
Closing as the issue appears to have been addressed by @benoit-lateltin.

**Comment by mmatlik** [comment]
Hi @benoit-lateltin.

Sorry to bother, but is it still applicable in the latest version of Jira Cloud? Using Standard Plan, and as a Site Administrator - neither Jira Automation nor any Workflow triggers seem to list the rule for this transition. However, the transition is still made once the GitHub PR gets merged. Thank you.

**Comment by benoit-lateltin** [comment]
Hello @mmatlik, 

I'm not sure, I think you should directly contact Atlassian or Github support teams.

**Comment by pavelbely** [comment]
@mmatlik did you resolve that?

Thank you in advance 🙏
