### ISSUE TITLE
Why does this app need "Read-only access to Organization members"?

### ISSUE THREAD

**Issue by keithalpichi** [integrations/jira#219]
My company got a notification that the Jira app by Github is requesting updated permissions. The new permission is "Read-only access to Organization members". I've read the [permission documentation](https://github.com/integrations/jira/blob/master/docs/permissions.md) but nothing explains what this permission is used for. Can anyone explain? Thank you.

If it's not in the documentation I'll be glad to add it.

**Comment by scepticulous** [comment]
Hi @keithalpichi ,
within the permission update Dialog, there should be a section with the title `Developer Note`, that explains why the additional permission is necessary.
I don't have the original text at hand, but it should be roughly about this:
`This permission is required to enable a new feature. Org admins can now manage subscriptions for any connected Jira instance.`

**Comment by keithalpichi** [comment]
Hi @scepticulous , thank you for the quick response.
