### ISSUE TITLE
When an installation fails the error page is generic

### ISSUE THREAD

**Issue by jnraine** [integrations/jira#232]
When there is a problem with the installation, you see a generic error message.

![62794609-60dea280-ba89-11e9-9ed2-efe96b827111](https://user-images.githubusercontent.com/300976/62794871-17db1e00-ba8a-11e9-8d42-1106ab88f241.png)

The error page comes from middleware that authenticates a request from Jira.

https://github.com/integrations/jira/blob/c903c49eed1a7bfce5e5e2ffece71158b1736f22/lib/frontend/verify-jira-middleware.js#L11

If installation can't be found, it may because it doesn't exist or it may be because [it isn't enabled](https://github.com/integrations/jira/blob/c903c49eed1a7bfce5e5e2ffece71158b1736f22/lib/models/installation.js#L44-L51).

### Suggestion

It would be useful if the error page was specific to the problem and directed the user to a solution.

**Comment by rachellerathbone** [comment]
Closing this issue as it looks like a [PR](https://github.com/integrations/jira/pull/233) was opened and merged 3 days later.
