### ISSUE TITLE
Set sync status to PAUSED on rate limit

### ISSUE THREAD

**Issue by jnraine** [integrations/jira#243]
When a sync hits the GitHub rate limit, we schedule it to run again when the rate limit resets.

https://github.com/integrations/jira/blob/b560ca8e9905c99cd9f63b4b9ce558e9b60ecfd8/lib/sync/installation.js#L154-L160

When this happens, the sync shows as ACTIVE but isn't actively being synced. This makes it difficult to tell the difference between a sync that has died due to an unexpected reason and a sync that is paused because we hit the rate limit.

Instead, when delaying the sync due to an exceeded rate limit, let's set the sync status to PAUSED.

![image](https://user-images.githubusercontent.com/300976/63292504-a87be000-c27a-11e9-9c17-e9e739aed013.png)

**Comment by rachellerathbone** [comment]
Closing as it looks like this was addressed with @240.
