### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by jnraine** [integrations/jira#247]
## Background

Presently, the app provides three methods for logging:

- Probot's [`context.log`](https://probot.github.io/docs/logging/): available within webhook event handlers.
- Probot's [`lib/logger`](https://github.com/probot/probot/blob/master/src/logger.ts): available anywhere when [manually required](https://github.com/integrations/jira/blob/fefe535ff0aaf2234e9bba198711f0f82aa71fa5/lib/jira/client/axios.js#L5).
- `console.log`: available everywhere.

The first two offer rich logging, including level and fields. An example message looks like this:

```json
{
  "name": "http",
  "id": "a92e1a0e-5f7a-4d01-b53e-43dafd7ea447",
  "level": 30,
  "msg": "POST /github/events 200 - 428.93 ms",
  "time": "2019-08-21T15:09:48.884Z",
}
```

`console.log` provides much less, outputting a string without level or fields:

```
Starting Jira sync
```

There are 10-15 instances of `console.log` and 20-30 calls to a Probot logger.

## Problem

While looking into a common error, I found it difficult to look through logs to build an understanding of how it might happen for a specific user. I was able to find logs for a few cases but wasn't able to build a complete picture.

There are two issues:

1. **There isn't a clear approach to logging for each area of the app.** Probot's [recommend logging pattern](https://probot.github.io/docs/logging/) works well within event handlers but isn't applicable in the web views or background jobs.
2. **Logs don't tell a story.** Messages in Loggly aren't consistently tagged with metadata about the user or request. This makes it difficult to use logs to look back and build a history of someone's experience with our integration. When compared to dotcom logs, where things like request ID and user ID reliably available to us, it's possible for developers or support to look back at what happened to confirm a user report or better understand how a bug occurs.

## Objectives

- [ ] **Good logging is easy.** A log with rich metadata should be available by default in every context.
- [ ] **Adding fields is easy.** A developer should be able to add log fields with a single line of code.
- [ ] **`console.log` isn't possible.** It's tempting to use `console.log`—it's always available and universally understood—but it provides low quality logs. When someone attempts to use it, a robot should tell them not to.

**Comment by rachellerathbone** [comment]
I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Once we take ownership of the app we plan to revisit logging and change the current implementation. Stay tuned 😄

**Comment by rachellerathbone** [comment]
We've updated logging in the new version of the app that will be released once the app transfer from GitHub to Atlassian is complete. Closing this issue as the work is now done.
