### ISSUE TITLE
PR Review Information not showing in JIRA

### ISSUE THREAD

**Issue by figmentbml** [integrations/jira#252]
I recently migrated my team to a managed JIRA instance and added this plugin.  While it appears that it is linking branches and PRs, it does not seem to be linking PR Review information (reviewer & state of review) in the Development Information panel.

**Comment by sgress454** [comment]
Having this issue as well, with the (now built-in?) Jira plugin.  The "reviewer" field in the Jira Pull Requests display never seems to be filled out. 

![image](https://user-images.githubusercontent.com/553428/74174444-66da5980-4c4d-11ea-9e69-0b0a0fb3b0e6.png)
![image](https://user-images.githubusercontent.com/553428/74174452-6b067700-4c4d-11ea-9ccc-8989acf269c3.png)

^ this PR has reviewers added and assigned, and the display in Jira shows nothing in the "Reviewer" column. Is there something we need to do to get this to populate? Or is it the reviewer column not supported by this app?

**Comment by nickangtc** [comment]
Same is happening for me as @sgress454 - no reviewer info pulled through despite there being a reviewer selected on GitHub.

![image](https://user-images.githubusercontent.com/5674362/75260517-01a86b80-57ea-11ea-8886-9cae96cc4d07.png)

I don't remember ever seeing this column being populated on our Jira Cloud instance. Either something is broken or it just doesn't sync this info

**Comment by nickangtc** [comment]
Hi @tebriel @zmoazeni, I'm inferring that you're the maintainers of this repo from the commit history. I was thinking to take a stab at this some time this weekend. Is a PR for this going to be welcomed?

**Comment by zmoazeni** [comment]
@nickangtc you are correct both of are currently actively maintaining this integration. I talked this over with the team internally and we would be very happy to review a feature for this. Thank you for volunteering!! ❤️ 

There are multiple ways to approach this. One is to simply do the work and open a PR. But if you wanted to discuss the implementation earlier feel free to ask any questions here and we will try to get you some timely answers. That way you can get a better picture of the scope of work prior to you investing too much effort into the feature.
 
Another approach some folks take is to open a "blank" PR, to discuss the proposed implementation, get a thumbs up, then feel more confident spending the rest of the effort building it out.

Whichever approach you take, please ping both me and @tebriel so that it'll be easier for us to cut through the notification noise. 

I'm looking forward to seeing what you propose!!

**Comment by nickangtc** [comment]
Thanks @zmoazeni for getting back with some suggestions on how to approach this, knowing that I haven't contributed to this project yet. Appreciate it.

Currently I haven't looked into the code yet (I just saw the stack, felt like it's probably doable and wrote my comment). Depending on whether it's a big task, I'll pick and approach and make sure to ping you both. Will try and work on this for a couple of hours this weekend. 👍

**Comment by zulfisync** [comment]
I would love to know the end result.

**Comment by ankurja** [comment]
When is this expected to be fixed ?

**Comment by nickangtc** [comment]
Sorry for the silence! I faced some difficulties setting up my dev env and didn't push through. This issue is up for whoever wants to take it forward.

**Comment by techgaun** [comment]
Any update on this? I'm looking for this feature as well and if no one is working on it, I may be able to get the work done for this.

**Comment by Luke-Py-Walker** [comment]
I'm investigating it right now, checking in with work on Monday to see if they got an ngrok sub so I can really start playing around. (the app uses subdomains, a premium ngrok feature)

**Comment by tebriel** [comment]
@Luke-Py-Walker the tooling does use subdomains, but you can use ngrok without it, you'll just need to update your jira app and your .env file every time the random domain that ngrok generates for you changes. (This occurs every time you restart ngrok).

**Comment by Luke-Py-Walker** [comment]
Hey @tebriel @zmoazeni , 

After my investigation, I've determined that most (if not all) of my changes will be made in `/lib/github/pull-request.js` and `/lib/transforms/pull-request.js`. I'm currently speccing out the best way to do this using [this link](https://developer.atlassian.com/cloud/jira/software/rest/api-group-development-information/#api-devinfo-0-10-bulk-post) as a reference for the Jira api. Do you know if there's anything else with more details on Jira's api?

**Comment by tebriel** [comment]
@Luke-Py-Walker that's the best document I have on using the jira API. It's the one I reference when I have questions (though it usually leads to more questions). Sorry I don't have any more/better details.

**Comment by zmoazeni** [comment]
@Luke-Py-Walker You can also ask us development questions either in this thread or in a new one. "Discussions" is now available for this repository so that's also an option.

If you would prefer to ask us privately, feel free to spin up a repo and invite myself to it and we can talk there too.

**Comment by techgaun** [comment]
It would be greatly appreciated if we could utilize the open platform here or Discussions. Looking forward to getting this feature in. Thanks all for working on this

**Comment by Luke-Py-Walker** [comment]
@techgaun @tebriel @zmoazeni I made a discussion for solving this issue at #375. Been busy this past week with traveling and work but I'm ready to knock this ticket out! 

I am having trouble with set-up tho 😅 I mentioned my issue in the discussion.

**Comment by Raul6469** [comment]
Hey there! 👋 

I just worked on this, and just opened #412 if you want to take a look :eyes: 

I have some failing tests to update, I'll take a look at this tomorrow

**Comment by atrigueiro** [comment]
Hi all,

We've implemented this feature and it's out in prod! https://github.com/integrations/jira/pull/447

Known limitations:
* It doesn't work on sync yet.
* Requested reviewers won't appear on the dev panel until they actually review the PR.

We're aware of both scenarios and they're in our backlog to be tackled at some point.

**Comment by flod1** [comment]
we have the same issue.

when it will be fixed?
