### ISSUE TITLE
GitHub and Jira Service Desk Integration 

### ISSUE THREAD

**Issue by bhushanrga** [integrations/jira#307]
While we integrate Jira and GitHub we can see development panel field in Jira Software projects issues, where we do everything.
But in case of Jira Service Desk projects it is not happening.
Is it possible to integrate Jira Service Desk with GitHub? like jira software.

**Comment by rachellerathbone** [comment]
Hi @bhushanrga. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by thombergs** [comment]
@bhushanrga no, sorry. This integration only works for Jira Software.

**Comment by rachellerathbone** [comment]
Hi @bhushanrga. Going to close this issue out. Please let us know if you have any other questions.
