### ISSUE TITLE
Multiple organizations?

### ISSUE THREAD

**Issue by takn** [integrations/jira#308]
Hi, is it possible to link a single app in Jira to multiple Github organizations?

**Comment by rachellerathbone** [comment]
Hi @takn. Yes, this is possible. On the page where you see you're installed org click 'Manage organizations'.

<img width="1538" alt="Screen Shot 2021-05-17 at 8 07 40 pm" src="https://user-images.githubusercontent.com/37155488/118471989-b4e0e580-b74b-11eb-8305-85bb6aec504a.png">

On the following screen you can then select the org you want and simply click 'Install'.

<img width="668" alt="Screen Shot 2021-05-17 at 8 08 19 pm" src="https://user-images.githubusercontent.com/37155488/118472056-c629f200-b74b-11eb-8d5d-e9e3ddc215af.png">

If the org you're after isn't listed, you'll need to click the 'Install Jira' link found on the above screen and go through the initial flow (something we're working to improve) of adding an org for the first time.

Going to close this out. Lmk if you have any other questions.

**Comment by hvaandres** [comment]
@rachellerathbone can you have Github Cloud and can you add your Github Enterprise under the same Jira account?
