### ISSUE TITLE
Can I use this integration with Jira Server 8.2

### ISSUE THREAD

**Issue by daemon-ian** [integrations/jira#309]
Hi, struggling to find if this works with Jira Server.

If it doesn't, can we get support for it?

**Comment by mira-silhavy** [comment]
Same here, since last week plugin stopped working. Showing commits and PRs from before 7th January 2020, but newer are not being shown anymore.

**Comment by tpiron** [comment]
Looks like it doesn't based on the readme:

> Requirements
This app officially supports GitHub.com and Jira Cloud. Support for GitHub Enterprise and/or Jira server may be considered in the future.

**Comment by rachellerathbone** [comment]
Hi @daemon-ian. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to triage' label so my team can discuss. I don't believe this is something we can support but will confirm before closing this out.

**Comment by rachellerathbone** [comment]
Hi @daemon-ian. We are currently is the process of migrating all customers off Jira Server and onto Jira Cloud. As this issue is related to a product that will be deprecated, I am going to close this issue. If you have any other requests/thoughts please feel free to open a new issue.
