### ISSUE TITLE
Can't see organization repositories

### ISSUE THREAD

**Issue by royt-via** [integrations/jira#315]
I'm part of an organization and I want to create a Jira<->Github integration to some of the organization's repos but I can't see them (on the Repository Aceess section, even though I have admin permissions on those repos) - only the ones I created on my account (not even those that I created on the organization account)

**Comment by rachellerathbone** [comment]
Hi @royt-via. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Are you still experiencing issues with this?

**Comment by rachellerathbone** [comment]
As it has been almost 2 months with no response, closing this issue.
