### ISSUE TITLE
Remove intermediary step for new GitHub installs.

### ISSUE THREAD

**Issue by primarilysnark** [integrations/jira#32]
When the app is installed to a new organization, it currently redirects back to the intermediary page and the user is forced to reselect their organization. Ideally, we'd take care of that for them so that it redirects back to Jira directly.

**Comment by rachellerathbone** [comment]
Hey @primarilysnark. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

The various flows of the app is something that we are actively working on and are in the process of determining how to improve this for our users. I'm going to close this issue out as we have a relevant ticket in our backlog. Hopefully you'll see an improvement in the not-too-distant future.
