### ISSUE TITLE
Show Jira information in GitHub

### ISSUE THREAD

**Issue by obuslovich** [integrations/jira#320]
How to configure Github for JIRA so that Jira issue last comments and Status are shown in the linked PR in GitHub?

**Comment by rachellerathbone** [comment]
Hi @obuslovich. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Just to make sure I'm understanding correctly - you want comments anyone makes in a Jira issue, along with it's corresponding status, to be reflected in linked GitHub PRs?

**Comment by rachellerathbone** [comment]
As it has been almost 2 months with no response, closing this issue.
