### ISSUE TITLE
Integration is not sending MERGE_COMMIT flag for merge commits

### ISSUE THREAD

**Issue by felipe-gdr** [integrations/jira#345]
According to the [Jira documentation](https://developer.atlassian.com/cloud/jira/software/rest/#api-group-Development-Information) for DevInfo, integrations can mark a commit as a merge commit while sending data via the `POST /rest/devinfo/0.10/bulk` endpoint.

```
flags
Array<string>

The set of flags for this commit

Unique items: true
Valid values: MERGE_COMMIT
```

This information is particularly useful for the new automation for jira feature, as we use it to decide whether rules should execute or not, and have other future plans for it too.

**Comment by zmoazeni** [comment]
Hi @felipe-gdr! Thanks for starting an issue!

Can you help me understand, how is this information displayed in Jira? What is the utility of marking merge commits?

Some screenshots would be wonderful!

**Comment by felipe-gdr** [comment]
Sure @zmoazeni :-) 

Merge commits are displayed differently in the devinfo panel. This is an example of a commit made from Bitbucket, which is sending the merge commit flag:

![image](https://user-images.githubusercontent.com/3858115/80774445-6a241800-8ba0-11ea-891c-a996661edc56.png)

Also, identifying a commit as a merge commit is important in the execution of automation rules. Users will likely not want most rules to execute for a merge commit.

I hope I was clear enough, let me know if I can help further :-)

**Comment by zmoazeni** [comment]
Thanks @felipe-gdr! That was great!

> Also, identifying a commit as a merge commit is important in the execution of automation rules. 

Can you expand on this a bit? Do you have a small example of an automation and how it would switch behavior based on this metadata? Is there an example scenario you have in mind?

**Comment by felipe-gdr** [comment]
Sure @zmoazeni !

First of all, if you're not familiar with Jira Automation already, I recommend having a look at [this page](https://www.atlassian.com/software/jira/features/automation) ;-) 

So, let's suppose a user creates an automation rule that will add a comment containing the commit message to an issue every time a commit containing the issue key in its message is pushed. Imagine they want to create a sort of log of commit messages in the Jira issue itself. In this case, users will probably not be interested in the merge commit message, since it might contain messages from all the previous commits, which would generate a lot of duplication.

**Comment by zmoazeni** [comment]
Interesting! Thanks @felipe-gdr. Let me run this by our team and get a ✅ - I think your solution is pretty lightweight as it just sets the metadata, and they can decide to use or ignore it. Thanks!

**Comment by willsmythe** [comment]
Should the suggestion described in https://github.com/integrations/jira/issues/144 also be considered?

**Comment by felipe-gdr** [comment]
@willsmythe we're discussing #144 internally and haven't made a decision. I believe you can keep #144 on the backlog for now and I'll write an update on it once we've decided on it.

(btw: I'm an Atlassian employee doing work in DevInfo)

**Comment by willsmythe** [comment]
@felipe-gdr - can you help us understand the possible impact to existing Jira customers with this change? Main concern is that we break or change behavior with a customer's existing automation rules when this new flag starts flowing across.

**Comment by felipe-gdr** [comment]
Sure @willsmythe .
We haven't yet rolled out the integration between GitHub and Jira Automation. Customers are not yet using this feature, so there will be no impact.

**Comment by mobeigi** [comment]
@zmoazeni @willsmythe Hi folks, I'm just wondering if there is any planned work on your roadmap to support this? As of right now, customers using Github are not able to correctly configure basic transitions rules as they cannot filter out these merge commits which results in unexpected behaviour. Thank you :)

**Comment by zmoazeni** [comment]
@mobeigi Unfortunately I'm no long working in this area within GitHub.

**Comment by rachellerathbone** [comment]
Hi @felipe-gdr. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

There is currently a PR open to merge in your changes and should be deployed in the coming week. Stay tuned 😄
