### ISSUE TITLE
Attach existing branch to ticket, attach multiple branches to ticket

### ISSUE THREAD

**Issue by showduhtung** [integrations/jira#352]
Many times during development, a ticket might be multi-purposed and might need multiple branches. Also, sometimes needed branches already exist, but are not yet associated with a particular ticket. It would be incredibly helpful to have that as an option. Doing what's recommended here:
https://stackoverflow.com/questions/25789652/jira-assign-an-existing-git-branch-to-an-issue

can introduce errors, and could result in a huge loss of work if done incorrectly.

**Comment by rachellerathbone** [comment]
Hi @showduhtung. You can add multiple branches to one Jira issue so long as the branch contains the issue key. If there are existing branches that don't include the issue key, they would need to be renamed to be identified by Jira and connected to the correct ticket.

<img width="932" alt="Screen Shot 2021-05-17 at 8 26 54 pm" src="https://user-images.githubusercontent.com/37155488/118474268-3d608580-b74e-11eb-9427-dd736dccfb2e.png">


Let me know if I've understood your issue so I can close this out/follow up.

**Comment by rachellerathbone** [comment]
As it has been almost 2 months with no response, closing this issue.
