### ISSUE TITLE
Received an email from Github with the subject "Deprecation notice for authentication via URL query parameters"

### ISSUE THREAD

**Issue by mseko** [integrations/jira#365]
Hi.

I received the email from GitHub with the subject line in the title.

The content of the email was as follows.

> On April 10th, 2020 at 02:50 (UTC) your application (JIRA) used an access token (with the User-Agent Apache-HttpClient/4.5.12 (Java/1.8.0_242)) as part of a query parameter to access an endpoint through the GitHub API.
Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

I am using this integrating application.
Did this application solve the problem described in the email?

**Comment by lsowen** [comment]
Looks like slightly more info on #311

**Comment by rachellerathbone** [comment]
Hi @mseko. Please let me know if your issue was addressed by the details in #311 so I can close this out/follow up.

**Comment by mseko** [comment]
Hi @rachellerathbone.
Resolved by the details in #311.
This Issue will be closed.
Thank you very much.

**Comment by rachellerathbone** [comment]
No worries. Thanks @mseko for getting back to me and for closing this issue. 

Please feel free to open any other issues if you need help or have requests/feedback. We have assigned a person from the team each week to look into issues so the response time will dramatically increase.
