### ISSUE TITLE
Drag and drop feature in system dashboard

### ISSUE THREAD

**Issue by igowthamr** [integrations/jira#369]
It would be good to have if we can able to drag and drop the items in system dashboard. It is difficult to accomplish the tasks by priority of story setter. But it should be useful the assigned is also provided with an option to priortize this

**Comment by rachellerathbone** [comment]
Hi @igowthamr. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Can you please provide a little more context around this? What system dashboard are you referring to? Provide screenshots if possible.

**Comment by rachellerathbone** [comment]
As it has been almost 2 months with no response, closing this issue. Please feel free to reopen if needed.
