### ISSUE TITLE
How do you get to the "Manage Jira Subscriptions"?

### ISSUE THREAD

**Issue by jwoods-ucsb** [integrations/jira#408]
Looking at the README and wondering how you get to the "Manage Jira Subscriptions" screenshot?

I am a Github Org Admin, and I am looking in Org Settings->Installed Third Party Apps. I see the Jira App installed, and when I select "Configure", it does not list the subscriptions. Is it located someplace else, or do I need an additional permission in Github?

Thanks

**Comment by rachellerathbone** [comment]
Hi @jwoods-ucsb. I believe to get to the screen you're looking for you click 'Manage organizations' from the GitHub configurations page > Mange.

<img width="1538" alt="Screen Shot 2021-05-17 at 8 07 40 pm" src="https://user-images.githubusercontent.com/37155488/118477315-e8267300-b751-11eb-862a-e383410f7e8a.png">

<img width="612" alt="Screen Shot 2021-05-17 at 8 53 31 pm" src="https://user-images.githubusercontent.com/37155488/118477370-f4aacb80-b751-11eb-9d8f-34a4accf4a69.png">

You should then see your list of subscriptions. Let me know if this helps so I can follow up/close.

**Comment by rachellerathbone** [comment]
As it has been almost 2 months with no response, closing this issue. Please feel free to reopen if needed.
