### ISSUE TITLE
Nothing to see in JIRA

### ISSUE THREAD

**Issue by snatvb** [integrations/jira#415]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1572963/111002737-fbeedb00-8396-11eb-9331-0ac19610782f.png">
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/1572963/111002756-0315e900-8397-11eb-9079-38c442e52538.png">

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1572963/111002815-217be480-8397-11eb-9b9e-cc96bf7ec793.png">

I tried thee times re-install your app. Nothing...

**Comment by snatvb** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/1572963/111002986-5c7e1800-8397-11eb-9093-9de15140f33d.png">
Full right side

**Comment by snatvb** [comment]
any help?

**Comment by Raul6469** [comment]
Hi @snatvb, it looks like you installed the GitHub App on selected repositories, maybe you forgot to add the one you are looking for? If it doesn't fix it, then I have no idea, sorry 😅

**Comment by snatvb** [comment]
Hello, @Raul6469 , nope, I selected needs repos...

**Comment by firemaples** [comment]
@snatvb Have you found any resolution?

**Comment by firemaples** [comment]
I got the same issue for two days, and I just fixed it by reinstall the extension on JIRA.

**Comment by snatvb** [comment]
@firemaples I tried it many times...
Maybe I have problems because I use Free plan in JIRA?

**Comment by firemaples** [comment]
@snatvb I use the free plan too.

There're my steps:
At first, I could not select any organization or repository on the extension's settings page on JIRA, so I opened Github's extension page to do the stuff.
After that, the extension's settings page on JIRA got blank and ran forever.
Then I reinstalled it on JIRA, and it works well now.

**Comment by snatvb** [comment]
@firemaples what I didn't try...doesn't work anything...

**Comment by Alecise** [comment]
Hi @snatvb, I may have find the answer (by stumbling upon the same mystery...).

In order to see the Development Panel on the issues, you need to have the permission to view it.

By default, users that are allowed to see the development Panel are those with a **Project role** of : developers, atlassian-addons-project-access
I didn't see it because I was an admin, and not a developer.

**I solved this by adding my role to the permission, in Cog Icon > Issues > Permission Schemes > {the permission scheme where the projects are involved} > View Development Tools** :)

Hope it will work for you

**Comment by rachellerathbone** [comment]
Hi @snatvb. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Please let me know if @Alecise's comment helped you resolve your issue so I can follow up/close.

**Comment by snatvb** [comment]
Hello @rachellerathbone,

No, I connected this app and I see control panel in Jira, auto converting also works in github issues. Just I don't see commits in Jira.

**Comment by rachellerathbone** [comment]
Ok, so let me first confirm a few things and ask some questions:

You've installed the GitHub app. Can you go to https://github.com/settings/apps/<your-github-app>/installations and confirm you see a similar view for the org you're working with:

<img width="751" alt="Screen Shot 2021-05-19 at 8 49 02 am" src="https://user-images.githubusercontent.com/37155488/118733141-1190ed00-b87f-11eb-9bb1-007a2df9f235.png">

If so, please click on the settings gear for your org and let me know if you have checked all repos or selected some:

<img width="415" alt="Screen Shot 2021-05-19 at 8 49 28 am" src="https://user-images.githubusercontent.com/37155488/118733233-3f763180-b87f-11eb-8fb7-65a4d5a4581e.png">


In Jira can you go to the navbar and click apps > manage your apps > then click on the accordion for the GitHub app and clicked get started (a button we are hoping to add some state to soon to change the wording post install).

<img width="298" alt="Screen Shot 2021-05-19 at 8 51 38 am" src="https://user-images.githubusercontent.com/37155488/118733351-70eefd00-b87f-11eb-9572-091f3a9469c5.png">

On the next screen, confirm that you have a sync status of complete for whatever org you are working with:

<img width="1517" alt="Screen Shot 2021-05-19 at 8 52 54 am" src="https://user-images.githubusercontent.com/37155488/118733479-ae538a80-b87f-11eb-84bd-e68f84f0cd74.png">

If all this checks out I'll continue to help you debug from there.

**Comment by snatvb** [comment]
Hi @rachellerathbone,

Sorry for long response.

I have such status in JIRA:
![image](https://user-images.githubusercontent.com/1572963/119236073-27800580-bb3e-11eb-8f12-89e598b54c9f.png)

It has such state in GitHub:
![image](https://user-images.githubusercontent.com/1572963/119236093-3b2b6c00-bb3e-11eb-802e-9e2cd618183b.png)

But I see nothing in https://github.com/settings/apps/
![image](https://user-images.githubusercontent.com/1572963/119236107-47172e00-bb3e-11eb-9dd8-2dbc112c5534.png)

**Comment by rachellerathbone** [comment]
Hi @snatvb. Thanks for the screenshots. They definitely help with situations like this. You wouldn't see anything in github app settings unless you made your own github app (used for contributing purposes).  I am curious as to why it's saying the sync status is complete but is showing 0/2 repos have synced 🤔 

From your Jira site you'll need to click on 'Projects' in the navbar and then select a project. Previously the project type had to be next gen but I think they've recently been renamed to team-managed software.

<img width="1760" alt="Screen Shot 2021-05-23 at 8 50 07 am" src="https://user-images.githubusercontent.com/37155488/119242825-8d06dd00-bba4-11eb-98ae-6c0364274f84.png">

In your project you then create a jira ticket:

<img width="279" alt="Screen Shot 2021-05-23 at 8 53 55 am" src="https://user-images.githubusercontent.com/37155488/119242834-97c17200-bba4-11eb-93ed-5822176a04d4.png">

When you create a branch, be sure to include the issue key from the ticket you just created. In my case, this is TEST-33:

<img width="198" alt="Screen Shot 2021-05-23 at 8 56 54 am" src="https://user-images.githubusercontent.com/37155488/119242874-ea9b2980-bba4-11eb-8c16-27c9ca5e7e81.png">

Same thing goes for commit messages:

<img width="219" alt="Screen Shot 2021-05-23 at 8 57 01 am" src="https://user-images.githubusercontent.com/37155488/119242879-f7b81880-bba4-11eb-8585-77d57225833d.png">

The issue keys in branches, commit messages, prs etc is essential as this helps Jira know which issue/s to attach things to.

<img width="198" alt="Screen Shot 2021-05-23 at 8 56 54 am" src="https://user-images.githubusercontent.com/37155488/119242898-29c97a80-bba5-11eb-993c-fa8ed8fedb05.png">

Now, when I go back to Jira (don't forgot to refresh!) I can see the symbol on my ticket indicating I have connected a branch/commit.

<img width="261" alt="Screen Shot 2021-05-23 at 9 04 36 am" src="https://user-images.githubusercontent.com/37155488/119242976-110d9480-bba6-11eb-8954-e50d4c476080.png">

And when I click on the ticket I see that I have 1 branch and 1 commit.

<img width="1032" alt="Screen Shot 2021-05-23 at 8 58 45 am" src="https://user-images.githubusercontent.com/37155488/119242978-1539b200-bba6-11eb-961a-aad2bff2273f.png">
 
And can also view both of these in the dev panel.

<img width="939" alt="Screen Shot 2021-05-23 at 8 59 03 am" src="https://user-images.githubusercontent.com/37155488/119242993-38fcf800-bba6-11eb-8a64-b169d0d58c17.png">

<img width="959" alt="Screen Shot 2021-05-23 at 8 59 08 am" src="https://user-images.githubusercontent.com/37155488/119242995-3c907f00-bba6-11eb-9bc5-697fee42f540.png">

**Comment by snatvb** [comment]
Hello @rachellerathbone,

My project has "Company-managed business" type.
![image](https://user-images.githubusercontent.com/1572963/119261044-2a323780-bbde-11eb-8ba8-c517a8436701.png)

As I understand, I must create new project with correct type and move issues to there.

I know how works smart commits, because I use JIRA in enterprise in my work :)
I try to use JIRA for my pet project.

I will try create test project with test repo and check that. I will give feedback, thanks.

**Comment by snatvb** [comment]
I can't change type to that with free plan. So I can suppose that I can't use smart commit's in free plan. Right?

**Comment by rachellerathbone** [comment]
I also work from a free account. I don't think you can change the type for an already created project. However, I only appear to have the options 'team-managed software' and 'company-managed software'. Did you go [here](https://www.atlassian.com/software/jira) to create your free account?

**Comment by snatvb** [comment]
@rachellerathbone, yes. I can create new project and there select template, where project type will be different(I suppose).
![image](https://user-images.githubusercontent.com/1572963/119317214-8483d480-bc80-11eb-9ccf-16e31b883278.png)

I think that project type(what do you have) is there:
![image](https://user-images.githubusercontent.com/1572963/119317460-cad93380-bc80-11eb-98c4-c05c7588866d.png)

But I can create project only by this templates for free:
![image](https://user-images.githubusercontent.com/1572963/119317573-e9d7c580-bc80-11eb-8bb7-db00469bcfa4.png)

But templates from "Software development" is not free for me.

**Comment by rachellerathbone** [comment]
When I created my Jira site I went to https://www.atlassian.com/software/jira, clicked 'Get it free' then followed the prompts. This allows be to create projects that are either 'team-managed software' or 'company-managed software'.

**Comment by snatvb** [comment]
Hi @rachellerathbone,

I created new project by Scrum and it works!
![image](https://user-images.githubusercontent.com/1572963/120246646-7e41b980-c279-11eb-98b7-08523addd342.png)

I think it has to do with the type of template project. I will update review comment for this App for JIRA.

Thank you!

**Comment by rachellerathbone** [comment]
That's great news @snatvb. Sorry you had so many issues getting this set up and working.

Is there anything else I can help with? If not, I'll go ahead and close this issue out.

**Comment by snatvb** [comment]
Hi @rachellerathbone,

I am not alone with this problem. I think this solution case must be in FAQ.
I don't have any questions. Thank you a lot. You really help me.
This issue can be closed.

**Comment by rachellerathbone** [comment]
So happy that I was able to help. 

I'll do some poking around to see who owns the FAQs to see if we can get that updated. I'll also chat with my team to see if there's a way we can better communicate the setup from the GitHub for Jira app.

**Comment by rachellerathbone** [comment]
@snatvb I've flagged this with my team. We are going to look into adding a support/FAQ/troubleshooting section to our app to better help our customers when they find themselves in situations such as yours.
