### ISSUE TITLE
Integrations permissions

### ISSUE THREAD

**Issue by richward1** [integrations/jira#462]
As a member of an organization, I've had to request permission for Jira to be integrated with a specific repo that I'm an admin on.
However, the owner's account has root access over the entire organization, and the setup prompts for permission to "Act on your behalf".
Can you confirm what this means please; is this just within the context of the repo that Jira would be connected to, or does it grant higher permissions than that?

**Comment by mboudreau** [comment]
Thanks for bringing this up.  We definitely should clarify this a bit more as the language isn't as succinct as it should be.

When giving access to your organisation on the app, you'll see specifically which permissions we're using which is:
- Contents: Read & Write
- Issues: Read & Write
- Metadata: Read (this is mandatory for Github apps)
- Pull requests: Read & Write

These permissions can only be applied to the repositories the owner has given the app access to.  This can be all repos under the organisation or only a select few that they've explicitly picked out.  So the answer to you question is **yes, this is only within the context of the repo you've allowed the app to access and it's important to remember that Github Apps simply cannot, in any way, gain higher privileges on behalf of the org admin** - [more on the limited API endpoints available to Github Apps here](https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps).

As for the "Act on your behalf" bit, that's just some legalese meaning that the integration can do stuff to the repos you've allowed the app to touch.  Feel free to look through the code to get a better understanding but what we're doing is fairly simple - we read information from repositories and add it to Jira. We do have plans in the near future to  improve the experience to save time and having to repeat information between Github and Jira.  We will have more on that later, so stay tuned.

I hope that's answered your question and your security concern.  Out of this, I will create a ticket for us to address the lack of clarity surrounding your concern.  

Cheers :)

**Comment by richward1** [comment]
Thank you, that's great to hear :)
