### ISSUE TITLE
JIRA load testing 

### ISSUE THREAD

**Issue by samkhamk** [integrations/jira#477]
Hello There,

First of all I am sorry this is not a issue but I need information,  

1. **GitHub for Jira** & **Jira GitHub Integration** are two separate thing or the same,
2. also I want to know how this integration will impact JIRA's performance, or can we monitor that performance within JIRA or we need to use tools like jmeter, etc.

Can you please guide me where I can get much information about above queries.

Regards,
SAM

**Comment by rachellerathbone** [comment]
Hey @samkhamk. 

1. Without links I can't be entirely sure what apps you're referencing (as there are a lot of GitHub apps in Jira) but this one is specifically the [GitHub for Jira](https://rachellerathbone.atlassian.net/plugins/servlet/ac/com.atlassian.jira.emcee/enduser-discover?project.key=TEST&project.id=10000#!/discover/app/com.github.integration.production) integration. This is the only GitHub/Atlassian owned integration.
2. I don't believe there should be any impact of Jira's performance so using monitoring tools should not be necessary.

Lmk if you have any other questions.

**Comment by rachellerathbone** [comment]
As it has been almost 2 months with no response, closing this issue. Please feel free to reopen if needed.
