### ISSUE TITLE
Are we looking at Jira Server support anymore?

### ISSUE THREAD

**Issue by jschanfung** [integrations/jira#547]
Resonating #309. My understanding is that for anyone who is on JIRA Server looking to integrate with github.com, they should stay with DVCS Connector until fully migrated to JIRA Cloud. I also noticed the [notes here back in 2018](https://community.atlassian.com/t5/Jira-articles/Everything-you-need-to-know-about-migrating-from-the-DVCS/ba-p/945910)

> _The DVCS Connector for GitHub.com (the GitHub enterprise connection has no date to move over yet) will no longer be supported as of June 30th, 2019._

[Given there are still years away until EOL on Jira Server](https://www.atlassian.com/migration/journey-to-cloud), just want to clarify what the current plan is?

**Comment by thombergs** [comment]
Hey @jschanfung,

that's right, we're not planning to add support for Jira Server in the "GitHub for Jira" integration. The link you shared, however, is about *Jira Cloud* and not Jira Server (i.e. DVCS Connector will no longer be supported for *Jira Cloud*). For Jira Server, it should still be supported until everyone is migrated to Cloud.
